### ISSUE TITLE
Default login and password

### ISSUE THREAD

**Issue by ycharbi** [bluecmd/sonic-builds#6]
Hello,
As is often the case, there is no mention of the login/password combination on the project download page (https://sonic.software/)...

What are they?

Thank you.

**Comment by bluecmd** [comment]
It's a good idea to add it to the site. They are the default ones, see https://github.com/sonic-net/SONiC/blob/master/doc/SONiC-User-Manual.md#21-default-login

**Comment by ycharbi** [comment]
Thank you for your reply.
I think it will be a plus for those who want to test this distribution quickly! Very good of you to have thought of the Qemu command line.

Have a nice day!
