### ISSUE TITLE
barefoot builds not followed anymore

### ISSUE THREAD

**Issue by dupont-y** [bluecmd/sonic-builds#7]
Hello and first of all, I'd like to thank you for your work, which makes it possible to find Sonic images quickly.
I've just seen that the script has been updated to retrieve the 202311 branches.
However, I also notice that barefoot constructions are no longer considered.
Although versions 202311 and master no longer build well (and worryingly, the https://github.com/sonic-net/sonic-buildimage/issues/16988 bug doesn't seem to be considered) versions 202305 and below continue to do so.

Is there any way to reintroduce barefoot in your script?

Best regards,

**Comment by bluecmd** [comment]
Sure, I can re-add it. I wasn't sure if anybody still used it as Intel has given up on Tofino. Give me a day or so and I'll put it back.

**Comment by bluecmd** [comment]
Done!

**Comment by dupont-y** [comment]
Thank you very much !

**Comment by andriidzhur** [comment]
> Thank you very much !

Hi!
Were you able to build actual master after barefoot was added back? I'm still fighting with it.
